### ISSUE TITLE
Deprecated SDK is resulting in broken servers

### ISSUE THREAD

**Issue by matt-halliday** [adobe/target-nodejs-sdk#1]
### Expected Behaviour

0.15.1 of the old SDK behaves the same as 0.15.0 of the old SDK and is only deprecated.

### Actual Behaviour

0.15.1 of the old SDK throws the following error when running a server on Express:
```
Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.wrappedResolveFilename [as _resolveFilename] (/home/ec2-user/www/node_modules/newrelic/lib/shimmer.js:465:42)
    at Function.Module._load (module.js:468:25)
    at Function.wrappedLoad [as _load] (/home/ec2-user/www/node_modules/newrelic/lib/shimmer.js:476:24)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/www/node_modules/@adobe/target-node-client/lib/index.js:26:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
module.js:540
    throw err;
    ^
```

### Reproduce Scenario (including but not limited to)

Running an express server with the latest old SDK. Will look to recreate after dealing with the fallout.

#### Platform and Version

Node 8 & Node 10 on linux or Mac

**Comment by XDex** [comment]
@matt-halliday Thank you for reporting this issue, I've just pushed a new version v0.15.2 with the fix.
The root cause was a recently updated `.gitignore` that made NPM ignore some of the dist files when packing and publishing.
